### ISSUE TITLE
JS Error on pages without graphs

### ISSUE THREAD

**Issue by cklosowski** [hlashbrooke/Seriously-Simple-Stats#1]
Looks like the Scripts for the Google data visualizer are running on all admin pages, not just the needed ones, seeing the following:
```
ReferenceError: google is not defined
http://rfcpodcast.com/wp-admin/post.php?post=65&action=edit:101

ReferenceError: google is not defined
http://rfcpodcast.com/wp-admin/post.php?post=65&action=edit:134
```

These are also being loaded twice on the edit page of a podcast episode

**Comment by hlashbrooke** [comment]
Thanks for reporting - I have redeployed v1 with the fix :)
